# Caminho do arquivo: /etc/rancher/k3s/config.yaml
# Exemplo para uso em laboratório/homelab

write-kubeconfig-mode: "0644"   # Permite que usuários não-root leiam o kubeconfig
cluster-cidr: "10.42.0.0/16"    # CIDR para o cluster
service-cidr: "10.43.0.0/16"    # CIDR para os serviços

